# -*- coding: utf-8 -*-

lenta_cities_master = {
    'cheboksary': 'Чебоксары',
    'nizhnij-novgorod': 'Нижний Новгород',
    'armavir': 'Армавир',
    'novorossijsk': 'Новороссийск',
    'krasnodar': 'Краснодар',
    'ufa': 'Уфа',
    'groznyj': 'Грозный',
    'voronezh': 'Воронеж',
    'belgorod': 'Белгород',
    'cheljabinsk': 'Челябинск',
    'magnitogorsk': 'Магнитогорск',
    'penza': 'Пенза',
    'saransk': 'Саранск',
    'petrozavodsk': 'Петрозаводск',
    'joshkar-ola': 'Йошкар-Ола',
    'orenburg': 'Оренбург',
    'orsk': 'Орск',
    'vologda': 'Вологда',
    'cherepovets': 'Череповец',
    'rostov': 'Ростов',
    'novocherkassk': 'Новочеркасск',
    'izhevsk': 'Ижевск',
    'volgograd': 'Волгоград',
    'volzhskij': 'Волжский',
    'toljatti': 'Тольятти',
    'samara': 'Самара',
    'taganrog': 'Таганрог',
    'uljanovsk': 'Ульяновск',
    'dimitrovgrad': 'Димитровград',
    'lipetsk': 'Липецк',
    'astrahan': 'Астрахань',
    'smolensk': 'Смоленск',
    'tula': 'Тула',
    'orel': 'Орел',
    'brjansk': 'Брянск',
    'ivanovo': 'Иваново',
    'vladimir': 'Владимир',
    'jaroslavl': 'Ярославль',
    'rjazan': 'Рязань',
    'stavropol': 'Ставрополь',
    'tver': 'Тверь',
    'syktyvkar': 'Сыктывкар',
    'moskva': 'Москва',
    'elino': 'Елино',
    'sergiev-posad': 'Сергиев Посад',
    'zheleznodorozhnyj': 'Железнодорожный',
    'istra': 'Истра',
    'kaluga': 'Калуга',
    'saratov': 'Саратов',
    'balakovo': 'Балаково',
    'engels': 'Энгельс',
    'novosibirsk': 'Новосибирск',
    'spb': 'Санкт-Петербург',
    'velikij-novgorod': 'Великий Новгород',
    'pskov': 'Псков',
    'murmansk': 'Мурманск',
    'zheleznovodsk': 'Железноводск',
    'naberezhnye-chelny': 'Набережные Челны',
    'nizhnekamsk': 'Нижнекамск',
    'almetevsk': 'Альметьевск',
    'nizhnij-tagil': 'Нижний Тагил',
    'perm': 'Пермь'
}


magnit_cities_subst = {
    u'Орёл': u'Орел'
}
